ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS breakfast_start TEXT DEFAULT '07:00';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS breakfast_end TEXT DEFAULT '10:30';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS lunch_start TEXT DEFAULT '12:30';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS lunch_end TEXT DEFAULT '15:30';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS dinner_start TEXT DEFAULT '19:00';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS dinner_end TEXT DEFAULT '22:30';
ALTER TABLE public.hotels ADD COLUMN IF NOT EXISTS city TEXT;
